name: 'ArgoCD Deploy'

on:
  workflow_call:
    secrets:
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: "AWS Secret Access Key"
      AWS_ACCESS_KEY_ID:
        required: true
        description: "AWS Access Key ID"
      AWS_REGION:
        required: true
        description: "AWS Region"
      AWS_SESSION_TOKEN:
        required: true
        description: "AWS Session Token"
      ECR_REPOSITORY:
        required: true
        description: "AWS ECR Repository Name"

jobs:
  deploy-argocd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get the ECR Repository URI
        id: get_uri
        run: |
          repository_uri=$(aws ecr describe-repositories --repository-names ${{ secrets.ECR_REPOSITORY }} --query 'repositories[0].repositoryUri' --output text)
          echo "::set-output name=repository_uri::$repository_uri"

      - name: Get the latest image tag from ECR
        id: get_latest_tag
        run: |
          latest_tag=$(aws ecr describe-images \
            --repository-name ${{ secrets.ECR_REPOSITORY }} \
            --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' \
            --output text)
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Update values.yaml with new image tag and repository URI
        run: |
          sed -i 's|repository: .*|repository: ${{ steps.get_uri.outputs.repository_uri }}|' ./app/charts/values.yaml
          sed -i 's|tag: ".*"|tag: "${{ steps.get_latest_tag.outputs.latest_tag }}"|' ./app/charts/values.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated update of values.yaml with latest image tag and repository URI"
          git push